replicaCount: 1

image:
  repository: ghcr.io/paulscherrerinstitute/scicat-rocrate
  tag: 2.4.4
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  probePath: /api/v1/health/live

ingress:
  hosts:
    - host: "{{ .Values.host }}"
      paths:
        - path: "/api/v1/zenodo"
          pathType: Prefix
