replicatCount: 1

image:
  repository: ghcr.io/paulscherrerinstitute/scicat-rocrate
  pullPolicy: Always
  tag: " sha256:35afc3cdeb8ffbe2979ea70d2d6f29ff6d4d010fc86be4bf0c68d147363ea1ea"
  # tag: 1.0.0-SNAPSHOT

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  probePath: /api/v1/health/live

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: "scicat-exporter-certificate"
