host: s3-broker.qa.psi.ch

scicat:
  backend_url: http://backend-next.scicat-qa
  job_manager_username: jobManager

upload_bucket: psi-upload-qa
retrieve_bucket: psi-retrieve-qa

ingress:
  enabled: false
