Scicat:
  # Backend URL from within the container
  Host: http://backend-next.scicat-development/api/v3
Transfer:
  StorageLocation: PSI
  Method: ExtGlobus
  ExtGlobus:
    TransferServiceUrl: "https://globus-proxy.development.psi.ch/globus/service"
    # Relies on the PSI_QA:/test2/demo directory being sync'd to /data
    SrcFacility: "PSI_QA"
    DstFacility: "PSI_DEV"
    CollectionRootPath: "/test2/demo"

MetadataExtractors:
  InstallationPath: ./extractors/
  SchemasLocation: ./schemas/
  DownloadMissingExtractors: true
  Timeout: 10m
  Extractors:
    - Name: LS
      GithubOrg: osc-em
      GithubProject: oscem-extractor-life
      Version: v2.0.2
      Executable: oscem-extractor-life
      # x86_64 tar.gz sha256sum
      Checksum: a596ade8dd115b57fb8d5aad56b96b0e0ad2820bf57252443c21d4c80278ca6e
      ChecksumAlg: sha256
      CommandLineTemplate: "-i '{{.SourceFolder}}' -o '{{.OutputFile}}' {{.AdditionalParameters}}"
      AdditionalParameters:
      - cs=2.7
      - gain_flip_rotate="None"
      # - epu="xmls/"
      Methods:
        - Name: Single Particle
          Schema: oscem_schemas_spa.schema.json
          Url: https://w3id.org/oscem-schemas/latest/spa/jsonschema/oscem_schemas_spa.schema.json
        - Name: Cellular Tomography
          Schema: oscem_cellular_tomo.json
          Url: https://w3id.org/oscem-schemas/latest/cellular_tomo/jsonschema/oscem_schemas_cellular_tomo.schema.json
        - Name: Tomography
          Schema: oscem_tomo.json
          Url: https://w3id.org/oscem-schemas/latest/subtomo/jsonschema/oscem_schemas_subtomo.schema.json
        - Name: Environmental Tomography
          Schema: oscem_env_tomo.json
          Url: https://w3id.org/oscem-schemas/latest/env_tomo/jsonschema/oscem_schemas_env_tomo.schema.json

    # - Name: MS
    #   GithubOrg: osc-em
    #   GithubProject: oscem-extractor-materials
    #   Version: v1.0.3
    #   Executable: MS_Metadata_reader
    #   Checksum: 56925ded88d6719d42eaafe66f98fce43a67f0132d6488ece8bcbcfd5f0704a3
    #   ChecksumAlg: sha256
    #   CommandLineTemplate: "-i '{{.SourceFolder}}' -o '{{.OutputFile}}'"
    #   Methods:
    #     - Name: Material Science
    #       Schema: oscem_general.json
    #       Url: https://w3id.org/oscem-schemas/latest/general/jsonschema/oscem_schemas_general.schema.json

WebServer:
  Auth:
    Disable: false
    SessionDuration: 28800
    Frontend:
      # User-facing frontend URL
      Origin: https://discovery.development.psi.ch
      RedirectPath: "/ingestor"
    OAuth2:
      ClientID: "openem-ingestor-demo"
      RedirectURL: "https://ingestor.development.psi.ch/callback"
      Scopes:
        - email
    OIDC:
      IssuerURL: "https://kc.development.psi.ch/realms/awi"
    JWT:
      UseJWKS: true
      JwksURL: "https://kc.development.psi.ch/realms/awi/protocol/openid-connect/certs"
      JwksSignatureMethods:
        - RS256
    RBAC:
      AdminRole: "ingestor-admin"
      CreateModifyTasksRole: "ingestor-write"
      ViewTasksRole: "ingestor-read"
  Paths:
    CollectionLocations:
      demo: "/test2/demo"
  MetadataExtJobs:
    ConcurrencyLimit: 4
    QueueSize: 200
  Other:
    BackendAddress: ingestor.development.psi.ch
    Port: 8080
    LogLevel: Debug
    SecureCookies: true
    DisableServiceAccountCheck: true