host: doi.psi.ch

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      google_verify: "{{ .Values.secretsJson.LP_GOOGLE_VERIFY }}"

env: 
  - name: GOOGLE_VERIFY
    valueFrom:
      secretKeyRef: 
        name: "{{ .Release.Name }}-s"
        key: google_verify

preRun: >-
  echo "google-site-verification: $GOOGLE_VERIFY" > /usr/share/nginx/html/$GOOGLE_VERIFY;
