non_interesting_parameters = [
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "S9",
    "S0",
    "0",
    "contributions",
    "techniques",
    "depth",
    "height",
    "width",
    "investigator",
    "Collaborators",
    "Investigator",
    "dataset_id",
    "scanNr",
    "moderator",
    "runNumber",
    "runNumbers",
    "Associated papers and projects",
    "Proposal",
    "Proposer",
    "beamlineSettings",
    "bitDepth",
    "dataCollection",
    "dataset",
    "dataset_dir_scat_extracted",
    "dataset_tensor_recon",
    "endianness",
    "format",
    "technique",
    "pixelSize",
    "spinRotAngle",
    "Sample",
    "dataProcessing",
    "description",
    "detector",
    "lemSetup",
    "magneticField",
    "sampleCryo",
    "measurement",
    "implantationEnergy",
    "scanParameters",
]

scientific_metadata_dict = {
    "beamlineParameters": {
        "Beam Energy": "dict(u:v)"
    },
    "experimentalSettings": {"beamEnergy": "string(v u)"},
    "sampleTemperature": "dict(u:v)"
}


