{{- range $name, $values := $.Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl $name $ }}
  labels:
    {{- include "helm_chart.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := $values }}
  {{ $k }}: | 
{{ tpl $v $ | indent 4}}
  {{- end }}
---
{{- end }}
