scicatUrl: "http://backend-next.scicat-development/"
port: 8080

defaults:
  - &openemFacility
    direction: SRC
    accessPath: profile.oidcClaims.resource_access.openem-ingestor-{{ toLower .Name}}.roles
    accessValue: ingestor-write

facilities:
  - name: PSI_DEV
    collection: deda66cc-9e42-49fc-a997-18a02abb7903
    direction: DST
    destinationPath: '/archive/{{ replace .Pid "." "-" }}/{{ .SourceFolder }}'
    accessPath: profile.oidcClaims.realm_access.roles
    accessValue: globus-proxy-user

  # Use QA as a source for some test transfers
  - name: DEMO
    collection: 394fb902-2fcf-4ffd-ba61-98d72e29dd0e
    direction: SRC
    accessPath: profile.oidcClaims.resource_access.openem-ingestor-demo.roles
    accessValue: ingestor-write

  # Disabled until they grant the service user access
  # - <<: *openemFacility
  #   name: UNIBAS
  #   collection: ab30321a-6f8f-488b-bf0a-f5afdd56398d
  #   sourcePath: "/collection_test/{{ .RelativeSourceFolder }}"
  - <<: *openemFacility
    name: UNIGE
    collection: d22fab58-5f80-47f1-a9a0-da36478ca41e
  - <<: *openemFacility
    name: UNIBE
    collection: 44e61e98-8dba-43ec-a862-c1fe82ac23d6
  - <<: *openemFacility
    name: DCIL
    collection: b3807ed3-db5e-4e6f-9831-fd8d72dfff8a
  - <<: *openemFacility
    name: EMPA
    collection: ed650f52-0235-4c40-a573-5f8de55841a6
  - name: EPFL-LBEM
    collection: ed650f52-0235-4c40-a573-5f8de55841a6
    direction: SRC
    accessPath: profile.oidcClaims.resource_access.openem-ingestor-lbem.roles
    accessValue: ingestor-write
