name: deploy-helm
description: "Helm deploy"

inputs:
  release: 
    description: helm release name
    required: true
    type: string
  namespace: 
    description: namespace of the release
    required: false
    type: string
    default: default
  chart: 
    description: chart to deploy
    required: true
    type: string
  values: 
    description: values to inject from command line
    required: false
    type: string
  value-files: 
    description: value files to concatenate with the -f option
    required: false
    type: string
  files: 
    description: helm values to set with set-file option
    required: false
    type: string
  secrets: 
    description: secrets to be set when creating the secret resource
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        echo $KUBECONFIG_FILE | base64 -d > conf;
        values=`echo ${{ inputs.value-files }} | tr -s ' ' ','`;
        set=`echo ${{ inputs.values }} | tr -s ' ' ','`;
        set_file=`echo ${{ inputs.files }} | tr -s ' ' ','`;
        echo $values;
        echo $set;
        echo $set_file;
        helm upgrade ${{ inputs.release }} ${{ inputs.chart }} \
          --namespace ${{ inputs.namespace }} --create-namespace \
          --install --wait --atomic --values=$values --set=$set \
          --set-file=$set_file --set-json secretsJson=${{ inputs.secrets }}
      shell: bash
      env: 
        KUBECONFIG: conf
