replicaCount: 1

image:
  repository: ghcr.io/paulscherrerinstitute/scicat-s3-broker
  tag: 0.4.1
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  probePath: /health

ingress:
  enabled: true
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: "s3-broker-certificate"

configMaps:
  "{{ .Release.Name }}-cm":
    config: "{{ .Values.AWS_CONFIG }}"

secrets:
  "{{ .Release.Name }}-s":
    type: Opaque
    data:
      job_manager_password: "{{ .Values.secretsJson.JOB_MANAGER_PASSWORD }}"
      credentials: "{{ .Values.secretsJson.S3_BROKER_CREDENTIALS }}"

env:
  - name: SCICAT_URL
    value: "{{ .Values.scicat.backend_url }}"
  - name: JOB_MANAGER_USERNAME
    value: "{{ .Values.scicat.job_manager_username }}"
  - name: JOB_MANAGER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "{{ .Release.Name }}-s"
        key: job_manager_password

volumes:
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"

volumeMounts:
  - name: config-volume
    mountPath: /env/config
    subPath: config
  - name: secrets-volume
    mountPath: /env/credentials
    subPath: credentials
