replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingresses:
  - enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: "{{ .Values.host }}"
        paths: 
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
        - "{{ .Values.host }}"
        secretName: "scicat-oaipmh-certificate"
  - enabled: true
    name: renku-redirect
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($http_accept = "application/ld+json") {
          return 302 "https://scicat-exporter.development.psi.ch/api/v1/zenodo/$1%2F$2/export";
        }
    hosts:
      - host: "{{ .Values.host }}"
        paths:
          - path: /detail/([^/]+)/([^/]+)
            pathType: ImplementationSpecific
run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      {{ .Values.preRun }}
      rm -f /usr/share/nginx/html/google43e14584df796f63.html;
      base64 -d /usr/share/nginx/html/assets/favicon.ico.b64 > /usr/share/nginx/html/favicon.ico;
      nginx -g "daemon off;"

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"

configMaps: 
  "{{ .Release.Name }}-cm":
    config.json: "{{ .Values.CONFIG }}"
    favicon.ico.b64: "{{ .Values.FAVICON | b64enc }}"

volumeMounts:
  - name: config-volume
    mountPath: /usr/share/nginx/html/assets/config.json
    subPath: config.json
  - name: config-volume
    mountPath: /usr/share/nginx/html/assets/favicon.ico.b64
    subPath: favicon.ico.b64
