replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-oaipmh-certificate"

run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      rm -f /usr/share/nginx/html/google43e14584df796f63.html;
      nginx -g "daemon off;"

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"

configMaps: 
  "{{ .Release.Name }}-cm":
    config.json: "{{ .Values.CONFIG }}"
    favicon.io: "{{ .Values.FAVICON }}"

volumeMounts:
  - name: config-volume
    mountPath: /usr/share/nginx/html/assets/config.json
    subPath: config.json
  - name: config-volume
    mountPath: /usr/share/nginx/html/assets/favicon.ico
    subPath: favicon.ico
