host: s3-broker.psi.ch

scicat:
  backend_url: http://backend-next.scicat-production
  job_manager_username: jobManager

upload_bucket: psi-upload
retrieve_bucket: psi-retrieve

ingress:
  enabled: false
