replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: /openaire/oai
          pathType: Exact
        - path: /oaipmh/oai
          pathType: Exact
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-oaipmh-certificate"

env:
  - name: ENVIRONMENT
    value: "{{ .Values.environment }}"
  - name: APP_ID
    value: oai-pmh-service
  - name: LOG_LEVEL
    value: info
  - name: ADMIN_USER_EMAIL
    value: awi-7903@psi.ch
  - name: SCICAT_BACKEND_URL
    value: "{{ .Values.backendUrl }}"
  - name: SERVICE_URL
    value: https://{{ .Values.host }}
  - name: SCICAT_ROUTE
    value: /oaipmh/oai
  - name: SERVICE_NAME
    value: oai-pmh-service
  - name: FACILITY_NAME
    value: PSI
