name: scicat-exporter

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/scicat-exporter.yml
      - .github/actions/deploy-helmfile/**
      - helm/helmfile-common.yaml
      - helm/configs/scicat-exporter/helmfile.yaml.gotmpl
      - helm/configs/scicat-exporter/development/**
      - helm/configs/scicat-exporter/values.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/scicat-exporter.yml
      - .github/actions/deploy-helmfile/**
      - helm/helmfile-common.yaml
      - helm/configs/scicat-exporter/helmfile.yaml.gotmpl
      - helm/configs/scicat-exporter/qa/**
      - helm/configs/scicat-exporter/values.yaml
  release:
    types: [published]

jobs:
  set_env:
    uses: ./.github/workflows/reusable.environment.yml

  deploy:
    if: (!needs.set_env.outputs.component) || needs.set_env.outputs.component == 'se'
    runs-on: ubuntu-latest
    environment: ${{ needs.set_env.outputs.environment }}
    needs:
      - set_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Open ssh tunnel
        uses: paulscherrerinstitute/scicat-ci/.github/actions/open-ssh-tunnel@main
        with:
          bastion_user: "${{ secrets.BASTION_USER }}"
          bastion_ssh_key: "${{ secrets.BASTION_SSH_KEY }}"

      - name: deploy
        uses: ./.github/actions/deploy-helmfile
        with:
          file: helm/configs/scicat-exporter/helmfile.yaml.gotmpl
          environment: "${{ needs.set_env.outputs.environment }}"
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          secrets: ${{ format('{{"EXPORTER_WHITELIST_IPS":"{0}"}}', secrets.EXPORTER_WHITELIST_IPS) }}
